In [18]:
import pandas as pd
import gzip
import json
import numpy as np

# LabWork

In [ ]:
# file_path_r = "../data/raw/Electronics.jsonl.gz"
# file_path_m = "../data/raw/meta_Electronics.jsonl.gz"

# n_rows = 2000

# reviews = []

# with gzip.open(file_path_r, "rt") as f:

#     for i, line in enumerate(f):
#         if i >= n_rows:
#             break
#         reviews.append(json.loads(line))

# meta = []
# with gzip.open(file_path_m, "rt") as f:

#     for i, line in enumerate(f):
#         if i >= n_rows:
#             break
#         meta.append(json.loads(line))


# review_df = pd.DataFrame(reviews)
# meta = pd.DataFrame(meta)

In [ ]:
# review_df.head()
# KEY: parent_asin
# core: title (descriptor), helpful_vote,
# nice to have: rating, text (cluttered/explode)
# no:  images, asin, user_id, timestamp, verified_purchase(not for query view), helpful_vote

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,3.0,Smells like gasoline! Going back!,First & most offensive: they reek of gasoline ...,[{'small_image_url': 'https://m.media-amazon.c...,B083NRGZMM,B083NRGZMM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1658185117948,0,True
1,1.0,Didn’t work at all lenses loose/broken.,These didn’t work. Idk if they were damaged in...,[],B07N69T6TM,B07N69T6TM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1592678549731,0,True
2,5.0,Excellent!,I love these. They even come with a carry case...,[],B01G8JO5F2,B01G8JO5F2,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1523093017534,0,True
3,5.0,Great laptop backpack!,I was searching for a sturdy backpack for scho...,[],B001OC5JKY,B001OC5JKY,AGGZ357AO26RQZVRLGU4D4N52DZQ,1290278495000,18,True
4,5.0,Best Headphones in the Fifties price range!,I've bought these headphones three times becau...,[],B013J7WUGC,B07CJYMRWM,AG2L7H23R5LLKDKLBEF2Q3L2MVDA,1676601581238,0,True

In [ ]:
# meta.head(10)
# KEY: parent_asin
# at min: main_category, title, features, description, details
# nice to haves: rating_number, average_rating, price, store 
# no: images, videos, subtitle, author, bought_together(empty)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Electronics,FS-1051 FATSHARK TELEPORTER V3 HEADSET,3.5,6,[],[Teleporter V3 The “Teleporter V3” kit sets a ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Fat Shark,"[Electronics, Television & Video, Video Glasses]","{'Date First Available': 'August 2, 2014', 'Ma...",B00MCW7G9M,None,NaN,NaN
1,All Electronics,Ce-H22B12-S1 4Kx2K Hdmi 4Port,5.0,1,"[UPC: 662774021904, Weight: 0.600 lbs]",[HDMI In - HDMI Out],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],SIIG,"[Electronics, Television & Video, Accessories,...",{'Product Dimensions': '0.83 x 4.17 x 2.05 inc...,B00YT6XQSE,None,NaN,NaN
2,Computers,Digi-Tatoo Decal Skin Compatible With MacBook ...,4.5,246,[WARNING: Please IDENTIFY MODEL NUMBER on the ...,[],19.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'AL 2Sides Video', 'url': 'https://...",Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop ...","{'Brand': 'Digi-Tatoo', 'Color': 'Fresh Marble...",B07SM135LS,None,NaN,NaN
3,AMAZON FASHION,NotoCity Compatible with Vivoactive 4 band 22m...,4.5,233,[☛NotoCity 22mm band is designed for Vivoactiv...,[],9.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],NotoCity,"[Electronics, Wearable Technology, Clips, Arm ...","{'Date First Available': 'May 29, 2020', 'Manu...",B089CNGZCW,None,NaN,NaN
4,Cell Phones & Accessories,Motorola Droid X Essentials Combo Pack,3.8,64,"[New Droid X Essentials Combo Pack, Exclusive ...",[all Genuine High Quality Motorola Made Access...,14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Verizon,"[Electronics, Computers & Accessories, Compute...",{'Product Dimensions': '11.6 x 6.9 x 3.1 inche...,B004E2Z88O,None,NaN,NaN
5,Sports & Outdoors,Raymarine Wi-Fish DownVision Blackbox Sonar wi...,3.5,25,[Black box Wi-Fi CHIRP DownVision sonar module...,[Transform your smartphone into a powerful CHI...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Raymarine,"[Electronics, Car & Vehicle Electronics, Marin...",{'Item Package Dimensions L x W x H': '9.3 x 8...,B00TX536EK,None,NaN,NaN
6,Cell Phones & Accessories,"QGHXO Band for Garmin Vivofit 4, Soft Silicone...",4.4,707,[Personalized Your Garmin Vivofit 4 Activity T...,"[Compatibility, Custom designed for your preci...",14.89,[{'thumb': 'https://m.media-amazon.com/images/...,[],QGHXO,"[Electronics, Wearable Technology, Arm & Wrist...",{'Package Dimensions': '6.85 x 4.37 x 1.1 inch...,B07BJ7ZZL7,None,NaN,NaN
7,Industrial & Scientific,Protech iPhone 4 microscope 60X Lens with illu...,3.8,6,[iPhone 4 Microscope with White 2-LED and Dete...,[This accessory will convert your iPhone 4 int...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ProTech,"[Electronics, Camera & Photo, Binoculars & Sco...","{'Light Source Type': 'LED', 'Color': 'Blue,Wh...",B005G99O2U,None,NaN,NaN
8,Computers,MOSISO Plastic Hard Shell Case & Keyboard Cove...,5.0,2,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],MOSISO,"[Electronics, Headphones, Earbuds & Accessorie...","{'Brand': 'MOSISO', 'Item Weight': '8 ounces',...",B01MCZP7RF,None,NaN,NaN
9,None,"Fishfinder, Depth Finder Poly Sun Cover for 3""...",4.4,86,"[Made of poly material, Available in black, Dr...",[Affordable and convenient way to cover your s...,10.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Unboxing Gamin Vivid ', 'url': 'ht...",Westlake Market,"[Electronics, Car & Vehicle Electronics, Marin...",{'Item Package Dimensions L x W x H': '7.32 x ...,B00R6R82HS,None,NaN,NaN

In [ ]:
# meta = meta.replace({None: np.nan})
# meta["bought_together"]
# meta[meta["bought_together"].notnull()]

Empty DataFrame
Columns: [main_category, title, average_rating, rating_number, features, description, price, images, videos, store, categories, details, parent_asin, bought_together, subtitle, author]
Index: []

In [ ]:
# meta["bought_together"].unique()

array([nan])

In [ ]:
hard_drop = ["images", "videos", "subtitle", "author", "bought_together"]
nice_but_drop = ["rating_number", "average_rating", "price", "store"]
full_drop = hard_drop + nice_but_drop
meta_subset = meta.drop(columns= full_drop)

In [33]:
meta_subset.to_csv("../data/processed/meta_subset.csv",index=False)

# EDA stuff

** N OTE TO CHECK THE "DETAILS" col which might be a dictonary? How do we want to handel that?

1) check how the files are in isolation

2) maybe can do some extra thing for the merged sample version?  (honestly optional)